name: Run IIT Bhilai Course Parser

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pdfplumber

      - name: Run course parser
        run: python scripts/fetch_courses.py

      - name: Commit and push result
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add generated/
          git commit -m "Update parsed courses" || echo "No changes to commit"
          git push
